import { OrderItem } from './order-item.model';
import { User } from './user.model';

export interface Order {
  orderId?: number; // Optional, as it will be generated by the backend
  orderDate: string;
  orderStatus: string;
  shippingAddress: string;
  billingAddress: string;
  totalAmount: number;
  user: User;
  orderItems: OrderItem[];
}
