export interface Loan {
    loanId?: number;             // Optional as it will be generated by the backend
    loanType: string;            // Type of the loan (e.g., "Home Loan", "Car Loan")
    description: string;         // Description of the loan
    interestRate: number;        // Interest rate for the loan
    maximumAmount: number;       // Maximum amount that can be borrowed
    repaymentTenure: number;     // Repayment tenure in months
    eligibility: string;         // Eligibility criteria for the loan
    documentsRequired: string;   // Required documents for applying for the loan
  }
  